# ISO list of countries
ISO_COUNTRIES = [
    { :iso => 'AF', :iso_name => 'AFGHANISTAN', :name => 'Afghanistan', :iso3 => 'AFG', :numcode => '004' },
    { :iso => 'AL', :iso_name => 'ALBANIA', :name => 'Albania', :iso3 => 'ALB', :numcode => '008' },
    { :iso => 'DZ', :iso_name => 'ALGERIA', :name => 'Algeria', :iso3 => 'DZA', :numcode => '012' },
    { :iso => 'AS', :iso_name => 'AMERICAN SAMOA', :name => 'American Samoa', :iso3 => 'ASM', :numcode => '016' },
    { :iso => 'AD', :iso_name => 'ANDORRA', :name => 'Andorra', :iso3 => 'AND', :numcode => '020' },
    { :iso => 'AO', :iso_name => 'ANGOLA', :name => 'Angola', :iso3 => 'AGO', :numcode => '024' },
    { :iso => 'AI', :iso_name => 'ANGUILLA', :name => 'Anguilla', :iso3 => 'AIA', :numcode => '660' },
    { :iso => 'AG', :iso_name => 'ANTIGUA AND BARBUDA', :name => 'Antigua and Barbuda', :iso3 => 'ATG', :numcode => '028' },
    { :iso => 'AR', :iso_name => 'ARGENTINA', :name => 'Argentina', :iso3 => 'ARG', :numcode => '032' },
    { :iso => 'AM', :iso_name => 'ARMENIA', :name => 'Armenia', :iso3 => 'ARM', :numcode => '051' },
    { :iso => 'AW', :iso_name => 'ARUBA', :name => 'Aruba', :iso3 => 'ABW', :numcode => '533' },
    { :iso => 'AU', :iso_name => 'AUSTRALIA', :name => 'Australia', :iso3 => 'AUS', :numcode => '036' },
    { :iso => 'AT', :iso_name => 'AUSTRIA', :name => 'Austria', :iso3 => 'AUT', :numcode => '040' },
    { :iso => 'AZ', :iso_name => 'AZERBAIJAN', :name => 'Azerbaijan', :iso3 => 'AZE', :numcode => '031' },
    { :iso => 'BS', :iso_name => 'BAHAMAS', :name => 'Bahamas', :iso3 => 'BHS', :numcode => '044' },
    { :iso => 'BH', :iso_name => 'BAHRAIN', :name => 'Bahrain', :iso3 => 'BHR', :numcode => '048' },
    { :iso => 'BD', :iso_name => 'BANGLADESH', :name => 'Bangladesh', :iso3 => 'BGD', :numcode => '050' },
    { :iso => 'BB', :iso_name => 'BARBADOS', :name => 'Barbados', :iso3 => 'BRB', :numcode => '052' },
    { :iso => 'BY', :iso_name => 'BELARUS', :name => 'Belarus', :iso3 => 'BLR', :numcode => '112' },
    { :iso => 'BE', :iso_name => 'BELGIUM', :name => 'Belgium', :iso3 => 'BEL', :numcode => '056' },
    { :iso => 'BZ', :iso_name => 'BELIZE', :name => 'Belize', :iso3 => 'BLZ', :numcode => '084' },
    { :iso => 'BJ', :iso_name => 'BENIN', :name => 'Benin', :iso3 => 'BEN', :numcode => '204' },
    { :iso => 'BM', :iso_name => 'BERMUDA', :name => 'Bermuda', :iso3 => 'BMU', :numcode => '060' },
    { :iso => 'BT', :iso_name => 'BHUTAN', :name => 'Bhutan', :iso3 => 'BTN', :numcode => '064' },
    { :iso => 'BO', :iso_name => 'BOLIVIA', :name => 'Bolivia', :iso3 => 'BOL', :numcode => '068' },
    { :iso => 'BA', :iso_name => 'BOSNIA AND HERZEGOVINA', :name => 'Bosnia and Herzegovina', :iso3 => 'BIH', :numcode => '070' },
    { :iso => 'BW', :iso_name => 'BOTSWANA', :name => 'Botswana', :iso3 => 'BWA', :numcode => '072' },
    { :iso => 'BR', :iso_name => 'BRAZIL', :name => 'Brazil', :iso3 => 'BRA', :numcode => '076' },
    { :iso => 'BN', :iso_name => 'BRUNEI DARUSSALAM', :name => 'Brunei Darussalam', :iso3 => 'BRN', :numcode => '096' },
    { :iso => 'BG', :iso_name => 'BULGARIA', :name => 'Bulgaria', :iso3 => 'BGR', :numcode => '100' },
    { :iso => 'BF', :iso_name => 'BURKINA FASO', :name => 'Burkina Faso', :iso3 => 'BFA', :numcode => '854' },
    { :iso => 'BI', :iso_name => 'BURUNDI', :name => 'Burundi', :iso3 => 'BDI', :numcode => '108' },
    { :iso => 'KH', :iso_name => 'CAMBODIA', :name => 'Cambodia', :iso3 => 'KHM', :numcode => '116' },
    { :iso => 'CM', :iso_name => 'CAMEROON', :name => 'Cameroon', :iso3 => 'CMR', :numcode => '120' },
    { :iso => 'CA', :iso_name => 'CANADA', :name => 'Canada', :iso3 => 'CAN', :numcode => '124' },
    { :iso => 'CV', :iso_name => 'CAPE VERDE', :name => 'Cape Verde', :iso3 => 'CPV', :numcode => '132' },
    { :iso => 'KY', :iso_name => 'CAYMAN ISLANDS', :name => 'Cayman Islands', :iso3 => 'CYM', :numcode => '136' },
    { :iso => 'CF', :iso_name => 'CENTRAL AFRICAN REPUBLIC', :name => 'Central African Republic', :iso3 => 'CAF', :numcode => '140' },
    { :iso => 'TD', :iso_name => 'CHAD', :name => 'Chad', :iso3 => 'TCD', :numcode => '148' },
    { :iso => 'CL', :iso_name => 'CHILE', :name => 'Chile', :iso3 => 'CHL', :numcode => '152' },
    { :iso => 'CN', :iso_name => 'CHINA', :name => 'China', :iso3 => 'CHN', :numcode => '156' },
    { :iso => 'CO', :iso_name => 'COLOMBIA', :name => 'Colombia', :iso3 => 'COL', :numcode => '170' },
    { :iso => 'KM', :iso_name => 'COMOROS', :name => 'Comoros', :iso3 => 'COM', :numcode => '174' },
    { :iso => 'CG', :iso_name => 'CONGO', :name => 'Congo', :iso3 => 'COG', :numcode => '178' },
    { :iso => 'CD', :iso_name => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', :name => 'Congo, the Democratic Republic of the', :iso3 => 'COD', :numcode => '180' },
    { :iso => 'CK', :iso_name => 'COOK ISLANDS', :name => 'Cook Islands', :iso3 => 'COK', :numcode => '184' },
    { :iso => 'CR', :iso_name => 'COSTA RICA', :name => 'Costa Rica', :iso3 => 'CRI', :numcode => '188' },
    { :iso => 'CI', :iso_name => 'COTE D\'IVOIRE', :name => 'Cote D\'Ivoire', :iso3 => 'CIV', :numcode => '384' },
    { :iso => 'HR', :iso_name => 'CROATIA', :name => 'Croatia', :iso3 => 'HRV', :numcode => '191' },
    { :iso => 'CU', :iso_name => 'CUBA', :name => 'Cuba', :iso3 => 'CUB', :numcode => '192' },
    { :iso => 'CY', :iso_name => 'CYPRUS', :name => 'Cyprus', :iso3 => 'CYP', :numcode => '196' },
    { :iso => 'CZ', :iso_name => 'CZECH REPUBLIC', :name => 'Czech Republic', :iso3 => 'CZE', :numcode => '203' },
    { :iso => 'DK', :iso_name => 'DENMARK', :name => 'Denmark', :iso3 => 'DNK', :numcode => '208' },
    { :iso => 'DJ', :iso_name => 'DJIBOUTI', :name => 'Djibouti', :iso3 => 'DJI', :numcode => '262' },
    { :iso => 'DM', :iso_name => 'DOMINICA', :name => 'Dominica', :iso3 => 'DMA', :numcode => '212' },
    { :iso => 'DO', :iso_name => 'DOMINICAN REPUBLIC', :name => 'Dominican Republic', :iso3 => 'DOM', :numcode => '214' },
    { :iso => 'EC', :iso_name => 'ECUADOR', :name => 'Ecuador', :iso3 => 'ECU', :numcode => '218' },
    { :iso => 'EG', :iso_name => 'EGYPT', :name => 'Egypt', :iso3 => 'EGY', :numcode => '818' },
    { :iso => 'SV', :iso_name => 'EL SALVADOR', :name => 'El Salvador', :iso3 => 'SLV', :numcode => '222' },
    { :iso => 'GQ', :iso_name => 'EQUATORIAL GUINEA', :name => 'Equatorial Guinea', :iso3 => 'GNQ', :numcode => '226' },
    { :iso => 'ER', :iso_name => 'ERITREA', :name => 'Eritrea', :iso3 => 'ERI', :numcode => '232' },
    { :iso => 'EE', :iso_name => 'ESTONIA', :name => 'Estonia', :iso3 => 'EST', :numcode => '233' },
    { :iso => 'ET', :iso_name => 'ETHIOPIA', :name => 'Ethiopia', :iso3 => 'ETH', :numcode => '231' },
    { :iso => 'FK', :iso_name => 'FALKLAND ISLANDS (MALVINAS)', :name => 'Falkland Islands (Malvinas)', :iso3 => 'FLK', :numcode => '238' },
    { :iso => 'FO', :iso_name => 'FAROE ISLANDS', :name => 'Faroe Islands', :iso3 => 'FRO', :numcode => '234' },
    { :iso => 'FJ', :iso_name => 'FIJI', :name => 'Fiji', :iso3 => 'FJI', :numcode => '242' },
    { :iso => 'FI', :iso_name => 'FINLAND', :name => 'Finland', :iso3 => 'FIN', :numcode => '246' },
    { :iso => 'FR', :iso_name => 'FRANCE', :name => 'France', :iso3 => 'FRA', :numcode => '250' },
    { :iso => 'GF', :iso_name => 'FRENCH GUIANA', :name => 'French Guiana', :iso3 => 'GUF', :numcode => '254' },
    { :iso => 'PF', :iso_name => 'FRENCH POLYNESIA', :name => 'French Polynesia', :iso3 => 'PYF', :numcode => '258' },
    { :iso => 'GA', :iso_name => 'GABON', :name => 'Gabon', :iso3 => 'GAB', :numcode => '266' },
    { :iso => 'GM', :iso_name => 'GAMBIA', :name => 'Gambia', :iso3 => 'GMB', :numcode => '270' },
    { :iso => 'GE', :iso_name => 'GEORGIA', :name => 'Georgia', :iso3 => 'GEO', :numcode => '268' },
    { :iso => 'DE', :iso_name => 'GERMANY', :name => 'Germany', :iso3 => 'DEU', :numcode => '276' },
    { :iso => 'GH', :iso_name => 'GHANA', :name => 'Ghana', :iso3 => 'GHA', :numcode => '288' },
    { :iso => 'GI', :iso_name => 'GIBRALTAR', :name => 'Gibraltar', :iso3 => 'GIB', :numcode => '292' },
    { :iso => 'GR', :iso_name => 'GREECE', :name => 'Greece', :iso3 => 'GRC', :numcode => '300' },
    { :iso => 'GL', :iso_name => 'GREENLAND', :name => 'Greenland', :iso3 => 'GRL', :numcode => '304' },
    { :iso => 'GD', :iso_name => 'GRENADA', :name => 'Grenada', :iso3 => 'GRD', :numcode => '308' },
    { :iso => 'GP', :iso_name => 'GUADELOUPE', :name => 'Guadeloupe', :iso3 => 'GLP', :numcode => '312' },
    { :iso => 'GU', :iso_name => 'GUAM', :name => 'Guam', :iso3 => 'GUM', :numcode => '316' },
    { :iso => 'GT', :iso_name => 'GUATEMALA', :name => 'Guatemala', :iso3 => 'GTM', :numcode => '320' },
    { :iso => 'GN', :iso_name => 'GUINEA', :name => 'Guinea', :iso3 => 'GIN', :numcode => '324' },
    { :iso => 'GW', :iso_name => 'GUINEA-BISSAU', :name => 'Guinea-Bissau', :iso3 => 'GNB', :numcode => '624' },
    { :iso => 'GY', :iso_name => 'GUYANA', :name => 'Guyana', :iso3 => 'GUY', :numcode => '328' },
    { :iso => 'HT', :iso_name => 'HAITI', :name => 'Haiti', :iso3 => 'HTI', :numcode => '332' },
    { :iso => 'VA', :iso_name => 'HOLY SEE (VATICAN CITY STATE)', :name => 'Holy See (Vatican City State)', :iso3 => 'VAT', :numcode => '336' },
    { :iso => 'HN', :iso_name => 'HONDURAS', :name => 'Honduras', :iso3 => 'HND', :numcode => '340' },
    { :iso => 'HK', :iso_name => 'HONG KONG', :name => 'Hong Kong', :iso3 => 'HKG', :numcode => '344' },
    { :iso => 'HU', :iso_name => 'HUNGARY', :name => 'Hungary', :iso3 => 'HUN', :numcode => '348' },
    { :iso => 'IS', :iso_name => 'ICELAND', :name => 'Iceland', :iso3 => 'ISL', :numcode => '352' },
    { :iso => 'IN', :iso_name => 'INDIA', :name => 'India', :iso3 => 'IND', :numcode => '356' },
    { :iso => 'ID', :iso_name => 'INDONESIA', :name => 'Indonesia', :iso3 => 'IDN', :numcode => '360' },
    { :iso => 'IR', :iso_name => 'IRAN, ISLAMIC REPUBLIC OF', :name => 'Iran, Islamic Republic of', :iso3 => 'IRN', :numcode => '364' },
    { :iso => 'IQ', :iso_name => 'IRAQ', :name => 'Iraq', :iso3 => 'IRQ', :numcode => '368' },
    { :iso => 'IE', :iso_name => 'IRELAND', :name => 'Ireland', :iso3 => 'IRL', :numcode => '372' },
    { :iso => 'IL', :iso_name => 'ISRAEL', :name => 'Israel', :iso3 => 'ISR', :numcode => '376' },
    { :iso => 'IT', :iso_name => 'ITALY', :name => 'Italy', :iso3 => 'ITA', :numcode => '380' },
    { :iso => 'JM', :iso_name => 'JAMAICA', :name => 'Jamaica', :iso3 => 'JAM', :numcode => '388' },
    { :iso => 'JP', :iso_name => 'JAPAN', :name => 'Japan', :iso3 => 'JPN', :numcode => '392' },
    { :iso => 'JO', :iso_name => 'JORDAN', :name => 'Jordan', :iso3 => 'JOR', :numcode => '400' },
    { :iso => 'KZ', :iso_name => 'KAZAKHSTAN', :name => 'Kazakhstan', :iso3 => 'KAZ', :numcode => '398' },
    { :iso => 'KE', :iso_name => 'KENYA', :name => 'Kenya', :iso3 => 'KEN', :numcode => '404' },
    { :iso => 'KI', :iso_name => 'KIRIBATI', :name => 'Kiribati', :iso3 => 'KIR', :numcode => '296' },
    { :iso => 'KP', :iso_name => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', :name => 'Korea, Democratic People\'s Republic of', :iso3 => 'PRK', :numcode => '408' },
    { :iso => 'KR', :iso_name => 'KOREA, REPUBLIC OF', :name => 'Korea, Republic of', :iso3 => 'KOR', :numcode => '410' },
    { :iso => 'KW', :iso_name => 'KUWAIT', :name => 'Kuwait', :iso3 => 'KWT', :numcode => '414' },
    { :iso => 'KG', :iso_name => 'KYRGYZSTAN', :name => 'Kyrgyzstan', :iso3 => 'KGZ', :numcode => '417' },
    { :iso => 'LA', :iso_name => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', :name => 'Lao People\'s Democratic Republic', :iso3 => 'LAO', :numcode => '418' },
    { :iso => 'LV', :iso_name => 'LATVIA', :name => 'Latvia', :iso3 => 'LVA', :numcode => '428' },
    { :iso => 'LB', :iso_name => 'LEBANON', :name => 'Lebanon', :iso3 => 'LBN', :numcode => '422' },
    { :iso => 'LS', :iso_name => 'LESOTHO', :name => 'Lesotho', :iso3 => 'LSO', :numcode => '426' },
    { :iso => 'LR', :iso_name => 'LIBERIA', :name => 'Liberia', :iso3 => 'LBR', :numcode => '430' },
    { :iso => 'LY', :iso_name => 'LIBYAN ARAB JAMAHIRIYA', :name => 'Libyan Arab Jamahiriya', :iso3 => 'LBY', :numcode => '434' },
    { :iso => 'LI', :iso_name => 'LIECHTENSTEIN', :name => 'Liechtenstein', :iso3 => 'LIE', :numcode => '438' },
    { :iso => 'LT', :iso_name => 'LITHUANIA', :name => 'Lithuania', :iso3 => 'LTU', :numcode => '440' },
    { :iso => 'LU', :iso_name => 'LUXEMBOURG', :name => 'Luxembourg', :iso3 => 'LUX', :numcode => '442' },
    { :iso => 'MO', :iso_name => 'MACAO', :name => 'Macao', :iso3 => 'MAC', :numcode => '446' },
    { :iso => 'MK', :iso_name => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', :name => 'Macedonia, the Former Yugoslav Republic of', :iso3 => 'MKD', :numcode => '807' },
    { :iso => 'MG', :iso_name => 'MADAGASCAR', :name => 'Madagascar', :iso3 => 'MDG', :numcode => '450' },
    { :iso => 'MW', :iso_name => 'MALAWI', :name => 'Malawi', :iso3 => 'MWI', :numcode => '454' },
    { :iso => 'MY', :iso_name => 'MALAYSIA', :name => 'Malaysia', :iso3 => 'MYS', :numcode => '458' },
    { :iso => 'MV', :iso_name => 'MALDIVES', :name => 'Maldives', :iso3 => 'MDV', :numcode => '462' },
    { :iso => 'ML', :iso_name => 'MALI', :name => 'Mali', :iso3 => 'MLI', :numcode => '466' },
    { :iso => 'MT', :iso_name => 'MALTA', :name => 'Malta', :iso3 => 'MLT', :numcode => '470' },
    { :iso => 'MH', :iso_name => 'MARSHALL ISLANDS', :name => 'Marshall Islands', :iso3 => 'MHL', :numcode => '584' },
    { :iso => 'MQ', :iso_name => 'MARTINIQUE', :name => 'Martinique', :iso3 => 'MTQ', :numcode => '474' },
    { :iso => 'MR', :iso_name => 'MAURITANIA', :name => 'Mauritania', :iso3 => 'MRT', :numcode => '478' },
    { :iso => 'MU', :iso_name => 'MAURITIUS', :name => 'Mauritius', :iso3 => 'MUS', :numcode => '480' },
    { :iso => 'MX', :iso_name => 'MEXICO', :name => 'Mexico', :iso3 => 'MEX', :numcode => '484' },
    { :iso => 'FM', :iso_name => 'MICRONESIA, FEDERATED STATES OF', :name => 'Micronesia, Federated States of', :iso3 => 'FSM', :numcode => '583' },
    { :iso => 'MD', :iso_name => 'MOLDOVA, REPUBLIC OF', :name => 'Moldova, Republic of', :iso3 => 'MDA', :numcode => '498' },
    { :iso => 'MC', :iso_name => 'MONACO', :name => 'Monaco', :iso3 => 'MCO', :numcode => '492' },
    { :iso => 'MN', :iso_name => 'MONGOLIA', :name => 'Mongolia', :iso3 => 'MNG', :numcode => '496' },
    { :iso => 'MS', :iso_name => 'MONTSERRAT', :name => 'Montserrat', :iso3 => 'MSR', :numcode => '500' },
    { :iso => 'MA', :iso_name => 'MOROCCO', :name => 'Morocco', :iso3 => 'MAR', :numcode => '504' },
    { :iso => 'MZ', :iso_name => 'MOZAMBIQUE', :name => 'Mozambique', :iso3 => 'MOZ', :numcode => '508' },
    { :iso => 'MM', :iso_name => 'MYANMAR', :name => 'Myanmar', :iso3 => 'MMR', :numcode => '104' },
    { :iso => 'NA', :iso_name => 'NAMIBIA', :name => 'Namibia', :iso3 => 'NAM', :numcode => '516' },
    { :iso => 'NR', :iso_name => 'NAURU', :name => 'Nauru', :iso3 => 'NRU', :numcode => '520' },
    { :iso => 'NP', :iso_name => 'NEPAL', :name => 'Nepal', :iso3 => 'NPL', :numcode => '524' },
    { :iso => 'NL', :iso_name => 'NETHERLANDS', :name => 'Netherlands', :iso3 => 'NLD', :numcode => '528' },
    { :iso => 'AN', :iso_name => 'NETHERLANDS ANTILLES', :name => 'Netherlands Antilles', :iso3 => 'ANT', :numcode => '530' },
    { :iso => 'NC', :iso_name => 'NEW CALEDONIA', :name => 'New Caledonia', :iso3 => 'NCL', :numcode => '540' },
    { :iso => 'NZ', :iso_name => 'NEW ZEALAND', :name => 'New Zealand', :iso3 => 'NZL', :numcode => '554' },
    { :iso => 'NI', :iso_name => 'NICARAGUA', :name => 'Nicaragua', :iso3 => 'NIC', :numcode => '558' },
    { :iso => 'NE', :iso_name => 'NIGER', :name => 'Niger', :iso3 => 'NER', :numcode => '562' },
    { :iso => 'NG', :iso_name => 'NIGERIA', :name => 'Nigeria', :iso3 => 'NGA', :numcode => '566' },
    { :iso => 'NU', :iso_name => 'NIUE', :name => 'Niue', :iso3 => 'NIU', :numcode => '570' },
    { :iso => 'NF', :iso_name => 'NORFOLK ISLAND', :name => 'Norfolk Island', :iso3 => 'NFK', :numcode => '574' },
    { :iso => 'MP', :iso_name => 'NORTHERN MARIANA ISLANDS', :name => 'Northern Mariana Islands', :iso3 => 'MNP', :numcode => '580' },
    { :iso => 'NO', :iso_name => 'NORWAY', :name => 'Norway', :iso3 => 'NOR', :numcode => '578' },
    { :iso => 'OM', :iso_name => 'OMAN', :name => 'Oman', :iso3 => 'OMN', :numcode => '512' },
    { :iso => 'PK', :iso_name => 'PAKISTAN', :name => 'Pakistan', :iso3 => 'PAK', :numcode => '586' },
    { :iso => 'PW', :iso_name => 'PALAU', :name => 'Palau', :iso3 => 'PLW', :numcode => '585' },
    { :iso => 'PA', :iso_name => 'PANAMA', :name => 'Panama', :iso3 => 'PAN', :numcode => '591' },
    { :iso => 'PG', :iso_name => 'PAPUA NEW GUINEA', :name => 'Papua New Guinea', :iso3 => 'PNG', :numcode => '598' },
    { :iso => 'PY', :iso_name => 'PARAGUAY', :name => 'Paraguay', :iso3 => 'PRY', :numcode => '600' },
    { :iso => 'PE', :iso_name => 'PERU', :name => 'Peru', :iso3 => 'PER', :numcode => '604' },
    { :iso => 'PH', :iso_name => 'PHILIPPINES', :name => 'Philippines', :iso3 => 'PHL', :numcode => '608' },
    { :iso => 'PN', :iso_name => 'PITCAIRN', :name => 'Pitcairn', :iso3 => 'PCN', :numcode => '612' },
    { :iso => 'PL', :iso_name => 'POLAND', :name => 'Poland', :iso3 => 'POL', :numcode => '616' },
    { :iso => 'PT', :iso_name => 'PORTUGAL', :name => 'Portugal', :iso3 => 'PRT', :numcode => '620' },
    { :iso => 'PR', :iso_name => 'PUERTO RICO', :name => 'Puerto Rico', :iso3 => 'PRI', :numcode => '630' },
    { :iso => 'QA', :iso_name => 'QATAR', :name => 'Qatar', :iso3 => 'QAT', :numcode => '634' },
    { :iso => 'RE', :iso_name => 'REUNION', :name => 'Reunion', :iso3 => 'REU', :numcode => '638' },
    { :iso => 'RO', :iso_name => 'ROMANIA', :name => 'Romania', :iso3 => 'ROM', :numcode => '642' },
    { :iso => 'RU', :iso_name => 'RUSSIAN FEDERATION', :name => 'Russian Federation', :iso3 => 'RUS', :numcode => '643' },
    { :iso => 'RW', :iso_name => 'RWANDA', :name => 'Rwanda', :iso3 => 'RWA', :numcode => '646' },
    { :iso => 'SH', :iso_name => 'SAINT HELENA', :name => 'Saint Helena', :iso3 => 'SHN', :numcode => '654' },
    { :iso => 'KN', :iso_name => 'SAINT KITTS AND NEVIS', :name => 'Saint Kitts and Nevis', :iso3 => 'KNA', :numcode => '659' },
    { :iso => 'LC', :iso_name => 'SAINT LUCIA', :name => 'Saint Lucia', :iso3 => 'LCA', :numcode => '662' },
    { :iso => 'PM', :iso_name => 'SAINT PIERRE AND MIQUELON', :name => 'Saint Pierre and Miquelon', :iso3 => 'SPM', :numcode => '666' },
    { :iso => 'VC', :iso_name => 'SAINT VINCENT AND THE GRENADINES', :name => 'Saint Vincent and the Grenadines', :iso3 => 'VCT', :numcode => '670' },
    { :iso => 'WS', :iso_name => 'SAMOA', :name => 'Samoa', :iso3 => 'WSM', :numcode => '882' },
    { :iso => 'SM', :iso_name => 'SAN MARINO', :name => 'San Marino', :iso3 => 'SMR', :numcode => '674' },
    { :iso => 'ST', :iso_name => 'SAO TOME AND PRINCIPE', :name => 'Sao Tome and Principe', :iso3 => 'STP', :numcode => '678' },
    { :iso => 'SA', :iso_name => 'SAUDI ARABIA', :name => 'Saudi Arabia', :iso3 => 'SAU', :numcode => '682' },
    { :iso => 'SN', :iso_name => 'SENEGAL', :name => 'Senegal', :iso3 => 'SEN', :numcode => '686' },
    { :iso => 'SC', :iso_name => 'SEYCHELLES', :name => 'Seychelles', :iso3 => 'SYC', :numcode => '690' },
    { :iso => 'SL', :iso_name => 'SIERRA LEONE', :name => 'Sierra Leone', :iso3 => 'SLE', :numcode => '694' },
    { :iso => 'SG', :iso_name => 'SINGAPORE', :name => 'Singapore', :iso3 => 'SGP', :numcode => '702' },
    { :iso => 'SK', :iso_name => 'SLOVAKIA', :name => 'Slovakia', :iso3 => 'SVK', :numcode => '703' },
    { :iso => 'SI', :iso_name => 'SLOVENIA', :name => 'Slovenia', :iso3 => 'SVN', :numcode => '705' },
    { :iso => 'SB', :iso_name => 'SOLOMON ISLANDS', :name => 'Solomon Islands', :iso3 => 'SLB', :numcode => '090' },
    { :iso => 'SO', :iso_name => 'SOMALIA', :name => 'Somalia', :iso3 => 'SOM', :numcode => '706' },
    { :iso => 'ZA', :iso_name => 'SOUTH AFRICA', :name => 'South Africa', :iso3 => 'ZAF', :numcode => '710' },
    { :iso => 'ES', :iso_name => 'SPAIN', :name => 'Spain', :iso3 => 'ESP', :numcode => '724' },
    { :iso => 'LK', :iso_name => 'SRI LANKA', :name => 'Sri Lanka', :iso3 => 'LKA', :numcode => '144' },
    { :iso => 'SD', :iso_name => 'SUDAN', :name => 'Sudan', :iso3 => 'SDN', :numcode => '736' },
    { :iso => 'SR', :iso_name => 'SURINAME', :name => 'Suriname', :iso3 => 'SUR', :numcode => '740' },
    { :iso => 'SJ', :iso_name => 'SVALBARD AND JAN MAYEN', :name => 'Svalbard and Jan Mayen', :iso3 => 'SJM', :numcode => '744' },
    { :iso => 'SZ', :iso_name => 'SWAZILAND', :name => 'Swaziland', :iso3 => 'SWZ', :numcode => '748' },
    { :iso => 'SE', :iso_name => 'SWEDEN', :name => 'Sweden', :iso3 => 'SWE', :numcode => '752' },
    { :iso => 'CH', :iso_name => 'SWITZERLAND', :name => 'Switzerland', :iso3 => 'CHE', :numcode => '756' },
    { :iso => 'SY', :iso_name => 'SYRIAN ARAB REPUBLIC', :name => 'Syrian Arab Republic', :iso3 => 'SYR', :numcode => '760' },
    { :iso => 'TW', :iso_name => 'TAIWAN, PROVINCE OF CHINA', :name => 'Taiwan, Province of China', :iso3 => 'TWN', :numcode => '158' },
    { :iso => 'TJ', :iso_name => 'TAJIKISTAN', :name => 'Tajikistan', :iso3 => 'TJK', :numcode => '762' },
    { :iso => 'TZ', :iso_name => 'TANZANIA, UNITED REPUBLIC OF', :name => 'Tanzania, United Republic of', :iso3 => 'TZA', :numcode => '834' },
    { :iso => 'TH', :iso_name => 'THAILAND', :name => 'Thailand', :iso3 => 'THA', :numcode => '764' },
    { :iso => 'TG', :iso_name => 'TOGO', :name => 'Togo', :iso3 => 'TGO', :numcode => '768' },
    { :iso => 'TK', :iso_name => 'TOKELAU', :name => 'Tokelau', :iso3 => 'TKL', :numcode => '772' },
    { :iso => 'TO', :iso_name => 'TONGA', :name => 'Tonga', :iso3 => 'TON', :numcode => '776' },
    { :iso => 'TT', :iso_name => 'TRINIDAD AND TOBAGO', :name => 'Trinidad and Tobago', :iso3 => 'TTO', :numcode => '780' },
    { :iso => 'TN', :iso_name => 'TUNISIA', :name => 'Tunisia', :iso3 => 'TUN', :numcode => '788' },
    { :iso => 'TR', :iso_name => 'TURKEY', :name => 'Turkey', :iso3 => 'TUR', :numcode => '792' },
    { :iso => 'TM', :iso_name => 'TURKMENISTAN', :name => 'Turkmenistan', :iso3 => 'TKM', :numcode => '795' },
    { :iso => 'TC', :iso_name => 'TURKS AND CAICOS ISLANDS', :name => 'Turks and Caicos Islands', :iso3 => 'TCA', :numcode => '796' },
    { :iso => 'TV', :iso_name => 'TUVALU', :name => 'Tuvalu', :iso3 => 'TUV', :numcode => '798' },
    { :iso => 'UG', :iso_name => 'UGANDA', :name => 'Uganda', :iso3 => 'UGA', :numcode => '800' },
    { :iso => 'UA', :iso_name => 'UKRAINE', :name => 'Ukraine', :iso3 => 'UKR', :numcode => '804' },
    { :iso => 'AE', :iso_name => 'UNITED ARAB EMIRATES', :name => 'United Arab Emirates', :iso3 => 'ARE', :numcode => '784' },
    { :iso => 'GB', :iso_name => 'UNITED KINGDOM', :name => 'United Kingdom', :iso3 => 'GBR', :numcode => '826' },
    { :iso => 'US', :iso_name => 'UNITED STATES', :name => 'United States', :iso3 => 'USA', :numcode => '840' },
    { :iso => 'UY', :iso_name => 'URUGUAY', :name => 'Uruguay', :iso3 => 'URY', :numcode => '858' },
    { :iso => 'UZ', :iso_name => 'UZBEKISTAN', :name => 'Uzbekistan', :iso3 => 'UZB', :numcode => '860' },
    { :iso => 'VU', :iso_name => 'VANUATU', :name => 'Vanuatu', :iso3 => 'VUT', :numcode => '548' },
    { :iso => 'VE', :iso_name => 'VENEZUELA', :name => 'Venezuela', :iso3 => 'VEN', :numcode => '862' },
    { :iso => 'VN', :iso_name => 'VIET NAM', :name => 'Viet Nam', :iso3 => 'VNM', :numcode => '704' },
    { :iso => 'VG', :iso_name => 'VIRGIN ISLANDS, BRITISH', :name => 'Virgin Islands, British', :iso3 => 'VGB', :numcode => '092' },
    { :iso => 'VI', :iso_name => 'VIRGIN ISLANDS, U.S.', :name => 'Virgin Islands, U.S.', :iso3 => 'VIR', :numcode => '850' },
    { :iso => 'WF', :iso_name => 'WALLIS AND FUTUNA', :name => 'Wallis and Futuna', :iso3 => 'WLF', :numcode => '876' },
    { :iso => 'EH', :iso_name => 'WESTERN SAHARA', :name => 'Western Sahara', :iso3 => 'ESH', :numcode => '732' },
    { :iso => 'YE', :iso_name => 'YEMEN', :name => 'Yemen', :iso3 => 'YEM', :numcode => '887' },
    { :iso => 'ZM', :iso_name => 'ZAMBIA', :name => 'Zambia', :iso3 => 'ZMB', :numcode => '894' },
    { :iso => 'ZW', :iso_name => 'ZIMBABWE', :name => 'Zimbabwe', :iso3 => 'ZWE', :numcode => '716' }
  ]